### ISSUE TITLE
Add a docker-compose stack

### ISSUE THREAD

**Issue by nkprince007** [zubroide/gitpab#1]
Please add a docker-composer stack so that this tool can be easily used by non-PHP developers. I come from a far off world of Python and Go and I have absolutely no idea how to work with php tools nor do I have the spare time to learn about them.

**Comment by mnvx** [comment]
@nkprince007 I has added docker-compose and instructions into readme. I well be pleasant if you will try to deploy project and give me feedback if problems will occurs.

## Installation using docker

You may obtain needed project ids from gitlab Api:
https://gitlab.com/api/v4/projects?private_token=your_private_token&membership=1 

Clone this repo and run containers from `docker` folder:

```bash
git clone git@github.com:zubroide/gitpab.git
cd gitpab/docker
export token="your_gitlab_private_token" \
    && export projects="project_id1,project_id2" \
    && docker-compose up --build app
```

Be patient. Loading data from Gitlab may take tens minutes at first time.

**Comment by nkprince007** [comment]
Uhm, thanks for the info. But, isn't the point of docker-compose having multiple smaller services? Shouldn't the webserver be separated from the actual application server, as in nginx separated from php?

**Comment by mnvx** [comment]
Yes, it would be better to separate app/Dockerfile to php, nginx and cron, but currently I have not time for it. If you could do it, it woild be great.
