### ISSUE TITLE
Try to get Data from Group

### ISSUE THREAD

**Issue by nisnis123** [zubroide/gitpab#12]
When starting the app, it tries to get data from group 2103748, even if I did not added any groups to my project. 
The request ends in a 404 Failure from Gitlab and the start process ist stopped.
Requested url: gitlab.com/api/v4/groups/2103748/milestones/?page=1&private_token=...&per_page=100&order_by=updated_at

When I run gitlab.com/api/v4/groups?private_token=... it returns an empty string as it should.

**Comment by mnvx** [comment]
This request occurs while reading milestones from project groups
