### ISSUE TITLE
I'm trying get start project with docker and I got this  - https://prnt.sc/lnzo2x. Could you help me with this?

### ISSUE THREAD

**Issue by lisovsk** [zubroide/gitpab#22]

**Comment by mnvx** [comment]
When you run container using command

```bash
export host="https://gitlab.com/" \
    && export token="your_gitlab_private_token" \
    && export projects="project_id1,project_id2" \
    && docker-compose up --build app
```

What is in variable `host="https://gitlab.com/"`?

**Comment by lisovsk** [comment]
When I run container I using host="https://gitlab.com/"

**Comment by mnvx** [comment]
Seems like you have problems with DNS. 
I has added option for ignoring of SSL verification.
Try to provide IP instead of host: `export host="https://35.231.145.151/"`

**Comment by lisovsk** [comment]
Unfortunately it didn't help(

**Comment by mnvx** [comment]
May be you have problem with passing system variables to docker compose. What operation system do you use?

**Comment by mnvx** [comment]
If you want do debug, you may specify values directly in [docker-compose.yml](https://github.com/zubroide/gitpab/blob/master/docker/docker-compose.yml#L15-L17)

**Comment by lisovsk** [comment]
Thank you very much! In that was the problem.
