### ISSUE TITLE
When I hosted app and came into /home I got this errors - http://prntscr.com/lty99e .  Can you help me with that?

### ISSUE THREAD

**Issue by lisovsk** [zubroide/gitpab#23]

**Comment by mnvx** [comment]
Looks like problem with access to cached files. Try to clear cache according to [update instruction](https://github.com/zubroide/gitpab#without-docker):

```bash
sudo php artisan cache:clear
```

**Comment by lisovsk** [comment]
It's fixed after I restart docker-compose up :)
