### ISSUE TITLE
Docker compose fails for gitpab-nginx on MacOS

### ISSUE THREAD

**Issue by rtodea** [zubroide/gitpab#39]
Hi @mnvx and @cebe,

First of all, a big thank you for the tool!

I found a small issue when setting it up on MacOS.
I have not spent that much time on it because I wanted it to just make it work.
Please have a look at the bug report attached bellow.

On an unrelated note, is there a route to update the reports from the UI?
I saw that restarting the stack will sync with gitlab, but maybe there is another easier way.

Best regards!

### Specs

| name | version |
| ------ | ------ |
|OS | MacOS Mojave 10.14.3 (18D109) |
|Docker | 18.09.3, build 774a1f4 |

### Steps

During the `docker-compose up --build` phase

```
ERROR: for gitpab-nginx  Cannot start service nginx: b'Mounts denied: \r\nThe path /data/gitpab/nginx/ssl\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
```

### Notes

To fix this alter the `docker-compose.yml` and change mounted volumes for `gitpab-nginx` to something Docker has permissions to.

E.g.
```
-      - /data/gitpab/nginx/ssl:/etc/ssl
+      - ./data/gitpab/nginx/ssl:/etc/ssl
```

Why is it necessary to mount to something system wide as `/data`?

**Comment by mnvx** [comment]
It is not necessary. It was added for supporting ssl certificate from host machine.
