### ISSUE TITLE
Loading data from Gtilab is empty

### ISSUE THREAD

**Issue by pepeshark** [zubroide/gitpab#42]
If I start with docker-compose or use this import:all command I will get an empty result. Something like this:
```gitpab-php | Cache cleared successfully.
gitpab-php | Loading data from Gtilab
gitpab-php | +--------------------+----------+
gitpab-php | | Entity             | Imported |
gitpab-php | +--------------------+----------+
gitpab-php | | projects           | 0        |
gitpab-php | | project_milestones | 0        |
gitpab-php | | group_milestones   | 0        |
gitpab-php | | issues             | 0        |
gitpab-php | | notes              | 0        |
gitpab-php | +--------------------+----------+
```
I use this command to start the containers:
```
export host="https://gitlab.com/" \
    && export token="your_gitlab_private_token" \
    && export projects="group/project_id1,group/project_id2" \
    && docker-compose up --build
```
Gitlab version:  11.9.8 (48528bc)

I have tried api with the right token and I have got a big JSON object with all of projects.
https://gitlab.com/api/v4/projects?private_token=your_private_token&membership=1

Do you have any idea why I get empty result with loading projects? Can I test it another way?
If you need more information please let me know.
Thnaks.

**Comment by mnvx** [comment]
Try to write project_id1 instead of group/project_id1. Int number.

**Comment by pepeshark** [comment]
sorry it was my misstake.
I put the project name instead of project id. For example projects="myFistProject,myBigProject"
The right example is the following:
projects="10,5,30"
You can find the project ID on Project details page below the "project name".
