### ISSUE TITLE
Add new project_id in runtime with docker-compose

### ISSUE THREAD

**Issue by pepeshark** [zubroide/gitpab#43]
I have run gitpab in docker enviroment.
I would like to add new project_id in runtime (without stop the app).
Is it possible?
Or I have to stop the app and then I have to run with new project_id with this command:
export host="https://gitlab.com/" \
    && export token="your_gitlab_private_token" \
    && export projects="project_id1,project_id2,new_project_id3" \
    && docker-compose up --build

**Comment by mnvx** [comment]
Need to stop and start container with new list of project id`s.
