### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mathdev112** [zubroide/gitpab#46]
Hi, I'm using docker and trying to run it locally but I receive an error "password authentication failed for user "gitpab". 

I have created the .env file using as an example .env.example, and change the variables to my variables, and there is no variable with user=gitpab. What do I need to do else?

Will appreciate your help, thanks.

**Comment by mnvx** [comment]
Where you have message 

> password authentication failed for user "gitpab"

In web interface or in console? Need more information.

**Comment by Araton95** [comment]
@mnvx  thanks for the reply, that was my mistake.
it works perfectly with docker.

**Comment by Araton95** [comment]
@mnvx by the way, the first time it takes more than 1 hour, and still no results. How I can know everything is ok or no? 

it writes  `gitpab-php exited with code 1` in many different colors.

**Comment by Araton95** [comment]
@mnvx 5 hours without result, I'm sure something is needed to do.

**Comment by mnvx** [comment]
Currently as I see cron task in Docker is not works. I will fix it soon.

**Comment by mnvx** [comment]
Hmm... I has checked current commit from master branch and scheduler is works after my morning changes. Are you use version from fresh commit?

**Comment by mnvx** [comment]
> gitpab-php exited with code 1

May you give more information from log?

**Comment by Araton95** [comment]
> Hmm... I has checked current commit from master branch and scheduler is works after my morning changes. Are you use version from fresh commit?

Yes, I pulled it today, 6-7 hours ago.

**Comment by Araton95** [comment]
> > gitpab-php exited with code 1
> 
> May you give more information from log?

Sure, at the end it shows:


```
...
Step 31/31 : ENTRYPOINT ["/root/entrypoint.sh"]
 ---> Using cache
 ---> 2c1d02896ff7

Successfully built 2c1d02896ff7
Successfully tagged gitpab_php:latest
Starting gitpab-db ... done
Recreating gitpab-php ... done
Recreating gitpab-nginx ... done
Attaching to gitpab-db, gitpab-php, gitpab-nginx
gitpab-db | 2019-06-18 14:33:17.251 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
gitpab-db | 2019-06-18 14:33:17.251 UTC [1] LOG:  listening on IPv6 address "::", port 5432
gitpab-db | 2019-06-18 14:33:17.264 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gitpab-db | 2019-06-18 14:33:17.297 UTC [24] LOG:  database system was shut down at 2019-06-18 14:32:57 UTC
gitpab-db | 2019-06-18 14:33:17.309 UTC [1] LOG:  database system is ready to accept connections
: invalid optionn/bash: -
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
....

```

**Comment by mnvx** [comment]
Strange.
I do not know reason, but try to use it without volume for code. Just comment next lines:

https://github.com/zubroide/gitpab/blob/f961f311b6325134bb9566c1d1579859df6b4a4b/docker-compose.yml#L28-L29

**Comment by Araton95** [comment]
> Strange.
> I do not know reason, but try to use it without volume for code. Just comment next lines:
> 
> https://github.com/zubroide/gitpab/blob/f961f311b6325134bb9566c1d1579859df6b4a4b/docker-compose.yml#L28-L29

It shows another error:

```
...
Step 30/31 : RUN composer dump-autoload
 ---> Running in 9e1da7aa0134
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

Fatal error: Uncaught ReflectionException: Class Illuminate\Contracts\Console\rffffffffffffffffffffff6 does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('Illuminate\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /var/www/html/artisan(33): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#5 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
ERROR: Service 'php' failed to build: The command '/bin/sh -c composer dump-autoload' returned a non-zero code: 255
```

**Comment by mnvx** [comment]
Try to delete php container and rebuild it without cached layers

**Comment by Araton95** [comment]
@mnvx done, it shows:

```
...
Step 31/31 : ENTRYPOINT ["/root/entrypoint.sh"]
 ---> Running in b14c7d3d4844
Removing intermediate container b14c7d3d4844
 ---> 56c475a36c9d

Successfully built 56c475a36c9d
Successfully tagged gitpab_php:latest
Pulling nginx (nginx:alpine)...
alpine: Pulling from library/nginx
e7c96db7181b: Already exists
f0e40e45c95e: Pull complete
Creating gitpab-db ... done
Creating gitpab-php ... done
Creating gitpab-nginx ... done
Attaching to gitpab-db, gitpab-php, gitpab-nginx
gitpab-db | The files belonging to this database system will be owned by user "postgres".
gitpab-db | This user must also own the server process.
gitpab-db |
gitpab-db | The database cluster will be initialized with locale "en_US.utf8".
gitpab-db | The default database encoding has accordingly been set to "UTF8".
gitpab-db | The default text search configuration will be set to "english".
gitpab-db |
gitpab-db | Data page checksums are disabled.
gitpab-db |
gitpab-db | fixing permissions on existing directory /var/lib/postgresql/data ... ok
gitpab-db | creating subdirectories ... ok
gitpab-db | selecting default max_connections ... 100
gitpab-db | selecting default shared_buffers ... 128MB
gitpab-db | selecting dynamic shared memory implementation ... posix
gitpab-db | creating configuration files ... ok
gitpab-db | running bootstrap script ... ok
gitpab-db | performing post-bootstrap initialization ... ok
gitpab-db | syncing data to disk ...
gitpab-db | WARNING: enabling "trust" authentication for local connections
gitpab-db | You can change this by editing pg_hba.conf or using the option -A, or
gitpab-db | --auth-local and --auth-host, the next time you run initdb.
gitpab-db | ok
gitpab-db |
gitpab-db | Success. You can now start the database server using:
gitpab-db |
gitpab-db |     pg_ctl -D /var/lib/postgresql/data -l logfile start
gitpab-db |
gitpab-db | waiting for server to start....2019-06-18 21:40:13.256 UTC [42] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gitpab-db | 2019-06-18 21:40:13.276 UTC [43] LOG:  database system was shut down at 2019-06-18 21:40:12 UTC
gitpab-db | 2019-06-18 21:40:13.283 UTC [42] LOG:  database system is ready to accept connections
: invalid optionn/bash: -
gitpab-db |  done
gitpab-db | server started
gitpab-db | CREATE DATABASE
gitpab-db |
gitpab-db |
gitpab-db | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
gitpab-db |
gitpab-db | 2019-06-18 21:40:13.732 UTC [42] LOG:  received fast shutdown request
gitpab-db | waiting for server to shut down....2019-06-18 21:40:13.736 UTC [42] LOG:  aborting any active transactions
gitpab-db | 2019-06-18 21:40:13.739 UTC [42] LOG:  background worker "logical replication launcher" (PID 49) exited with exit code 1
gitpab-db | 2019-06-18 21:40:13.740 UTC [44] LOG:  shutting down
gitpab-db | 2019-06-18 21:40:13.765 UTC [42] LOG:  database system is shut down
gitpab-db |  done
gitpab-db | server stopped
gitpab-db |
gitpab-db | PostgreSQL init process complete; ready for start up.
gitpab-db |
gitpab-db | 2019-06-18 21:40:13.843 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
gitpab-db | 2019-06-18 21:40:13.843 UTC [1] LOG:  listening on IPv6 address "::", port 5432
gitpab-db | 2019-06-18 21:40:13.853 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gitpab-db | 2019-06-18 21:40:13.874 UTC [60] LOG:  database system was shut down at 2019-06-18 21:40:13 UTC
gitpab-db | 2019-06-18 21:40:13.881 UTC [1] LOG:  database system is ready to accept connections
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
gitpab-php exited with code 1
...
```

what's the optimal time for waiting, until it will pull all data from the Gitlab API?

**Comment by mnvx** [comment]
Message

> gitpab-php exited with code 1

Prints unlimited times or it passes through some time?

**Comment by Araton95** [comment]
> Message
> 
> > gitpab-php exited with code 1
> 
> Prints unlimited times or it passes through some time?

For now, its shown 15 times and the amount is increased.

**Comment by Araton95** [comment]
@mnvx hi, I tried to launch it with the 1.4.0 release, now it shows an error when I log in:

```
ErrorException (E_WARNING)
file_put_contents(
/data/www/gitpab/storage/framework/cache/data/85/5f/855f92484c8c414d36c1b25cb24876e30229cbbf): 
failed to open stream: 
No such file or directory
```

**Comment by asharabu** [comment]
Hi,

I am also getting below error,

> gitpab-php exited with code 1
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
gitpab-php exited with code 1
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: 

> 

Anybody able to fix this error?

**Comment by mnvx** [comment]
@asharabu may you give more data from log? And what is your OS?

**Comment by asharabu** [comment]
Hi,

I am trying  this in docker for windows in the windows 10. 

> 
gitpab-nginx | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: /etc/nginx/conf.d/default.conf differs from the packages version, exiting
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
gitpab-nginx | /docker-entrypoint.sh: Configuration complete; ready for start up
gitpab-nginx | 2020/06/10 06:59:45 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:13
gitpab-nginx | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:13
gitpab-nginx | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
gitpab-nginx | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
gitpab-nginx | 10-listen-on-ipv6-by-default.sh: /etc/nginx/conf.d/default.conf differs from the packages version, exiting
gitpab-nginx | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
gitpab-nginx | /docker-entrypoint.sh: Configuration complete; ready for start up
gitpab-db |
gitpab-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
gitpab-db |
gitpab-db | 2020-06-10 06:59:39.524 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
gitpab-db | 2020-06-10 06:59:39.526 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
gitpab-db | 2020-06-10 06:59:39.526 UTC [1] LOG:  listening on IPv6 address "::", port 5432
gitpab-db | 2020-06-10 06:59:39.799 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
gitpab-db | 2020-06-10 06:59:40.197 UTC [25] LOG:  database system was interrupted; last known up at 2020-06-10 06:19:32 UTC
gitpab-db | 2020-06-10 06:59:54.705 UTC [25] LOG:  database system was not properly shut down; automatic recovery in progress
gitpab-db | 2020-06-10 06:59:54.820 UTC [25] LOG:  redo starts at 0/1645DC0
gitpab-db | 2020-06-10 06:59:54.820 UTC [25] LOG:  invalid record length at 0/1645DF8: wanted 24, got 0
gitpab-db | 2020-06-10 06:59:54.820 UTC [25] LOG:  redo done at 0/1645DC0
gitpab-db | 2020-06-10 06:59:55.618 UTC [1] LOG:  database system is ready to accept connections
gitpab-php exited with code 1
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
gitpab-php exited with code 1
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
gitpab-php exited with code 1
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -
: invalid optionn/bash: -

>
