### ISSUE TITLE
Mistake in docker-compose.yml

### ISSUE THREAD

**Issue by d00mw01f** [zubroide/gitpab#49]
Service for DB uses volume with path `/var/lib/postgresql` while actual postgres volume path is `/var/lib/postgresql/data/`.

Due to this mistake 2 volumes are being created and data is being saved in automatically created volume `/var/lib/postgresql/data/` while volume `/var/lib/postgresql` remains empty. On each `docker-compose down` automatically created volume hasn't usage anymore and new volume will be created in next `docker-compose up`

**Comment by mnvx** [comment]
Yes. May you make pull request?

**Comment by d00mw01f** [comment]
Sure.

**Comment by mnvx** [comment]
Thanks
