### ISSUE TITLE
In the table of spent time to add a column with date when actually was time spended.

### ISSUE THREAD

**Issue by lisovsk** [zubroide/gitpab#5]

**Comment by mnvx** [comment]
Yes, I plan to make this feature. Currently this column only in CSV file.

**Comment by mnvx** [comment]
I could do it after 28th september. If someone will do it early - you are welcome!

**Comment by lisovsk** [comment]
But in CSV file  can be displayed only current date. When I changed the date to an other  date it's did't work. Can you fix it? 
http://prntscr.com/kw7yk3 => http://prntscr.com/kw7ywv

**Comment by mnvx** [comment]
Wow, I dont knew about this feature of Gitlab (how to mark spent time in hindsight). Will be fixed later.

**Comment by mnvx** [comment]
Ow... I had mixed up issues. Done in #3
