### ISSUE TITLE
error: freetype-config not found.

### ISSUE THREAD

**Issue by lisovsk** [zubroide/gitpab#51]
I got this error ( http://prntscr.com/oiimr3 ) in the process docker-compose up. Can you help me with that?

**Comment by mnvx** [comment]
May you try to change first line in Dockerfile [like here](https://github.com/docker-library/php/issues/865#issuecomment-511140588)

    FROM php:7.3-fpm

to

    FROM php:7.3-fpm-stretch

**Comment by lisovsk** [comment]
Thanks, it helped but got another problem - http://prntscr.com/oob3h3
And I already installed mcrypt

**Comment by mnvx** [comment]
Updated dependencies and deploy scripts
