### ISSUE TITLE
Cannot start gitpab: duplicate key value violates unique constraint "contributor_pkey"

### ISSUE THREAD

**Issue by juanluisbaptiste** [zubroide/gitpab#58]
Hi,

I'm trying to start gitpab with the following command:

```
export host="https://gitlab.com/" \
    && export token="xxxxxxxxxxxxxxxxxx" \
    && export projects="yyyyyyy" \
    && docker-compose up

```
First time it came up ok, then I stopped the container to start it with a different gitlab project id and now I'm getting this error:

```
gitpab-db | 2020-04-14 16:27:31.100 UTC [76] ERROR:  duplicate key value violates unique constraint "contributor_pkey"
gitpab-db | 2020-04-14 16:27:31.100 UTC [76] DETAIL:  Key (id)=(1246543) already exists.
gitpab-db | 2020-04-14 16:27:31.100 UTC [76] STATEMENT:  insert into "contributor" ("id", "name", "username", "state", "avatar_url", "web_url", "updated_at", "created_at") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id"

```

I removed containers (docker-compose rm -f -v) and deleted all volumes

```
# docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
gitpab_db
gitpab_code

Total reclaimed space: 77.85MB

```

It looks like the database is not being deleted ? I even cloned again the project to do a fresh start but the error persists.

**Comment by mnvx** [comment]
If you are need to delete database, try to delete volume manually.

docker volume ls
docker volume rm ...

вт, 14 апр. 2020 г., 19:55 Juan Luis Baptiste <notifications@github.com>:

**Comment by juanluisbaptiste** [comment]
That's the whole point of this report, that I already have deleted all volumes and I get that error:

```
# docker-compose rm -f -v            
Going to remove gitpab-nginx, gitpab-php, gitpab-db
Removing gitpab-nginx ... done
Removing gitpab-php   ... done
Removing gitpab-db    ... done
# docker volume prune                
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
gitpab_code
gitpab_db

Total reclaimed space: 78.12MB
# docker volume ls 
DRIVER              VOLUME NAME
#
```
After that I run the command as the documentation says:

```
# export host="https://gitlab.com/" \
    && export token="xxxxxxxxxxxxxxxxxx" \
    && export projects="yyyyyyy" \
    && docker-compose up
```

And I get the reported error all the time I try.

**Comment by juanluisbaptiste** [comment]
I just noticed that even with the error the application seems to be working fine. Probably the error was present the first time too and I didn 't noticed it, I just tested on another machine and the error appears too.

**Comment by mnvx** [comment]
Oh, yes, it is postgres error in container `gitpab-db`. This error ignores in try-catch block. You are may ignore it.

**Comment by juanluisbaptiste** [comment]
Excellent, thanks.

**Comment by GRomR1** [comment]
@mnvx I am getting the same errors. May be will be the best to disable this error in the code or change the sql insert query?

**Comment by mnvx** [comment]
Of course. I will be glad if you are or anyone more will do it. This log looks like very minor bug for me, so I cant to do it in nearest time.
