### ISSUE TITLE
The project does not run after installation

### ISSUE THREAD

**Issue by andreypesoshin** [zubroide/gitpab#67]
I used the guide from README which is:
```
git clone git@github.com:zubroide/gitpab.git
cd gitpab
export host="https://gitlab.com/" \
    && export token="your_gitlab_private_token" \
    && export projects="project_id1,project_id2" \
    && docker-compose up --build
```

The environment is centos 7 server on a virtual machine with Docker version 19.03.9, build 9d988398e7 

and fail with an error:
```
(1/1) ErrorExceptionfile_put_contents(/var/www/html/storage/framework/cache/data/85/5f/855f92484c8c414d36c1b25cb24876e30229cbbf): failed to open stream: No such file or directory
--
```

The full crash log is attached.
Is there anything I can do with this error on my side? Thanks in advance

[gitpab-crash.txt](https://github.com/zubroide/gitpab/files/5413782/gitpab-crash.txt)

**Comment by mnvx** [comment]
Looks like problem with access to files.

Try to comment next line

https://github.com/zubroide/gitpab/blob/142b8885b74d5adaf5e0f2e4a3161edd24d3775f/docker-compose.yml#L15

And next lines

https://github.com/zubroide/gitpab/blob/142b8885b74d5adaf5e0f2e4a3161edd24d3775f/docker-compose.yml#L28-L29

**Comment by v0ff4k** [comment]
massive human-hours project, framework npm and all for  gitlab client with GUI 

but i got problem with run after docker build
```gitpab-php | wait-for-it.sh: waiting 180 seconds for db:5432
gitpab-php | wait-for-it.sh: db:5432 is available after 0 seconds
gitpab-php | PostgreSQL started
gitpab-php | Init project
gitpab-db | 2022-11-14 20:33:23.105 UTC [126] LOG:  incomplete startup packet
gitpab-php | 
gitpab-php | Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/html/bootstrap/app.php:14
gitpab-php | Stack trace:
gitpab-php | #0 /var/www/html/artisan(20): require_once()
gitpab-php | #1 {main}
gitpab-php |   thrown in /var/www/html/bootstrap/app.php on line 14
```

also build did not starts correctly
```
RUN composer install --no-dev --no-autoloader
```
replaced with:

```
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin && \
    echo "alias composer='composer'" >> /root/.bashrc && \
    composer
```

and after that - the build was successful! but run - failed.
Thx for ur work !

**Comment by mnvx** [comment]
Fixed, please try again
