### ISSUE TITLE
Only some of the time spent is now imported

### ISSUE THREAD

**Issue by IreneIsaiah** [zubroide/gitpab#79]
For all of our developers, regardless of which filters or search options we use, gitpab now only shows a selection of the time spent entries.
We believe this started after GitLab released time tracking reports (GitLab 13.12, https://gitlab.com/gitlab-org/gitlab/-/issues/271409).
 
We have not been able to find a pattern in regards to what is imported and what is not.

**Comment by mnvx** [comment]
About month ago Gitlab API was changed and these changes were taken into account in last commits in this repository. Are you pulled updates? I recommend to run `php artisan import:all --full` after update to rewrite history of spent time from gitlab.

**Comment by IreneIsaiah** [comment]
According to this website that is for non-docker only. We are running it through Docker.

**Comment by mnvx** [comment]
Are you pulled last changes from this repo (`git pull`)?

**Comment by IreneIsaiah** [comment]
Yes, of course.

**Comment by mnvx** [comment]
May you give example of lost data? How was formed comment about time spent, how it looks in response of Gitlab API?

**Comment by IreneIsaiah** [comment]
We have been trying different things now. We were all using desktop application (on macs), with various versions of the engine (20.x or 19.x). None of this worked. One of our developers have now managed to get it working by downgrading to version 18, and now desktop application.
