### ISSUE TITLE
Whoops! There was on error

### ISSUE THREAD

**Issue by guidtz** [zubroide/gitpab#9]
Hello,
  I'll build gitpad and when I'm login I have a lot of errors : 
`ErrorException thrown with message "file_put_contents(/data/www/gitpab/storage/framework/cache/data/85/5f/855f92484c8c414d36c1b25cb24876e30229cbbf): failed to open stream: Permission denied"

Stacktrace:
#65 ErrorException in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
#64 file_put_contents in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
#63 Illuminate\Filesystem\Filesystem:put in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:65
#62 Illuminate\Cache\FileStore:put in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:195
#61 Illuminate\Cache\Repository:put in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:327
#60 Illuminate\Cache\Repository:remember in /data/www/gitpab/vendor/spatie/laravel-permission/src/PermissionRegistrar.php:52
#59 Spatie\Permission\PermissionRegistrar:getPermissions in /data/www/gitpab/vendor/spatie/laravel-permission/src/Models/Permission.php:155
#58 Spatie\Permission\Models\Permission:getPermissions in /data/www/gitpab/vendor/spatie/laravel-permission/src/Models/Permission.php:91
#57 Spatie\Permission\Models\Permission:findByName in /data/www/gitpab/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php:111
#56 App\User:hasPermissionTo in /data/www/gitpab/vendor/spatie/laravel-permission/src/PermissionRegistrar.php:34
#55 Spatie\Permission\PermissionRegistrar:Spatie\Permission\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php:354
#54 Illuminate\Auth\Access\Gate:callBeforeCallbacks in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php:309
#53 Illuminate\Auth\Access\Gate:raw in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php:249
#52 Illuminate\Auth\Access\Gate:Illuminate\Auth\Access\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Support/Collection.php:376
#51 Illuminate\Support\Collection:every in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php:253
#50 Illuminate\Auth\Access\Gate:check in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Auth/Access/Authorizable.php:18
#49 Illuminate\Foundation\Auth\User:can in /data/www/gitpab/vendor/spatie/laravel-permission/src/Middlewares/PermissionMiddleware.php:22
#48 Spatie\Permission\Middlewares\PermissionMiddleware:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#42 Illuminate\Auth\Middleware\Authenticate:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#24 Illuminate\Pipeline\Pipeline:then in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
#23 Illuminate\Routing\Router:runRouteWithinStack in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#22 Illuminate\Routing\Router:runRoute in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#21 Illuminate\Routing\Router:dispatchToRoute in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#20 Illuminate\Routing\Router:dispatch in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/fideloper/proxy/src/TrustProxies.php:56
#17 Fideloper\Proxy\TrustProxies:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /data/www/gitpab/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /data/www/gitpab/public/index.php:55
`

How can I help you to debug the problem ?

Regards

**Comment by mnvx** [comment]
Are you use docker-compose? Chrck permissions to `/data/www/gitpab/storage/**`

**Comment by guidtz** [comment]
I don't know why but now It's works ... I use named volume in my docker-compose. 
We could close this issue 
Sorry !
