### ISSUE TITLE
"php artisan db:seed" and "php artisan db:seed" fails

### ISSUE THREAD

**Issue by KeldNielsen86** [zubroide/gitpab#98]
Hi

I got the following error when installing your project and running one of the following commands  
"php artisan db:seed" and "php artisan db:seed" 

```
In RepositoryAbstractEloquent.php line 70:

  Declaration of App\Model\Repository\RepositoryAbstractEloquent::count(): int should be compatible with Prettus\Repository\Eloquent\BaseRepository::count(array $where = Array, $columns = '*')

```

**Comment by mnvx** [comment]
Hi. Maybe this linked with your php version. I will update update this project several weeks later.

**Comment by KeldNielsen86** [comment]
I am using php 7.4 - I had a problem running composer install on the project, something like "the package.json file is not complete, please run composer update"  and I did, perhaps I got a package which is too new for this project? else I followed the guide.

**Comment by KeldNielsen86** [comment]
which php version is recommended?

**Comment by KeldNielsen86** [comment]
and are there any other way (workaround) I can do in order to get this project to work on my server (linux).? perhaps create the user by myself and fill the database with the seeders manually

**Comment by mnvx** [comment]
PHP 7.4 must be ok

**Comment by KeldNielsen86** [comment]
any news in this issue?.  Ii would really like to use this time tool

**Comment by mnvx** [comment]
Fixed
